greensmoothie/config/routes.rb
Greensmoothie::Application.routes.draw do
  resources :ailments

  resources :recipes

  root 'ailments#index'

end

greensmoothie/app/models/ailment.rb
class Ailment < ActiveRecord::Base
	has_many :ailment_recipes
	has_many :recipes, through: :ailment_recipes

	def name
		"#{name}"
	end
end

greensmoothie/app/controllers/ailments_controller.rb
class AilmentsController < ApplicationController
  before_action :set_ailment, only: [:show, :edit, :update, :destroy]

  # GET /ailments
  # GET /ailments.json
  #@ailments stores all of the ailments objects in db
  #corresponding index view, will render all of those objects in the view
  def index
    @ailments = Ailment.all
  end

  # GET /ailments/1
  # GET /ailments/1.json
  def show
  end

  # GET /ailments/new
  #create a new object, persist data to ailment object, push to db, form on new page -- ailment object with name attribute, someone types that in and clicks submit, fires up a POST request, which persists data into db using Ailment.new function, then when you go to show page, try to find that specific object, will grab using object_id
  def new
    @ailment = Ailment.new
  end

  # GET /ailments/1/edit
  def edit
  end

  # POST /ailments
  # POST /ailments.json
  def create
    @ailment = Ailment.new(ailment_params)

    respond_to do |format|
      if @ailment.save
        format.html { redirect_to @ailment, notice: 'Ailment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ailment }
      else
        format.html { render action: 'new' }
        format.json { render json: @ailment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ailments/1
  # PATCH/PUT /ailments/1.json
  def update
    respond_to do |format|
      if @ailment.update(ailment_params)
        format.html { redirect_to @ailment, notice: 'Ailment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ailment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ailments/1
  # DELETE /ailments/1.json
  def destroy
    @ailment.destroy
    respond_to do |format|
      format.html { redirect_to ailments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ailment
      @ailment = Ailment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ailment_params
      params.require(:ailment).permit(:name)
    end
end

# class AilmentsController < ApplicationController

#   def index
#     if params[:search].nil?
#       @ailments = []
#     else
#       quoted_search_terms = params[:search].split(",").collect do |recipe|
#         "\"+#{recipe.strip}\""
#       end.join(" ")

#       @ailments = []
#       begin
#         @search = Ailment.search do
#           fulltext quoted_search_terms do
#             highlight :page_content
#             minimum_match 1
#           end
#         end

#         @ailments = @search.results
#         @ailments << Ailment.first if @ailments.count == 0
#       rescue
#         @ailments = Ailment.all.sample(5)
#       end
#       @ailment_name = @ailments[0..4].collect(&:name).shuffle.first
#       @ailment_url = Ailment.find_by(:name => @ailment_name).try(:url)

#       respond_to do |format|
#         format.html { render action: "index" }
#         format.js
#       end
#     end
#   end

# end

greensmoothie/app/helpers/ailments_helper.rb
module AilmentsHelper
end

greensmoothie/app/views/ailments/_form.html.erb
<div class="close-out"><%= link_to "x", "#" %></div>
  <div class="result-modal">
  <p>
    <h2 class="ailment-recipe">Here is your smoothie:</h2>
    <h2><%= link_to @recipe_name.upcase, "http://www.wikipedia.org/#{@disease_url}", :target => "blank" %></h2>
  </p>
  <%= image_tag "skull-and-crossbones.png", :id => "skull-image" %>
  <p class="disclaimer"><strong>Disclaimer:</strong><br>
    Nutrition is a supplement, not a substitute, for conventional medicine.  Please consider food allergies, carb/fruit sugar content, medicine contraindications, etc. before consuming new foods.</p>
  <h3 class="try-again-link"><%= link_to "Meh? Try again for a new recipe >>", "#" %></h3>
  </div>







<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

greensmoothie/app/views/ailments/_recipe_result.html.erb
  <div class="close-out"><%= link_to "x", "#" %></div>
  <div class="result-model">
  <p>
    <h2 class="result">Here is a green smoothie for you to try:</h2>
    <h2><%= link_to @recipe_name.upcase, "http://www.wikipedia.org/#{@disease_url}", :target => "blank" %></h2>
  </p>
  <%= image_tag "skull-and-crossbones.png", :id => "skull-image" %>
  <p class="disclaimer"><strong>Disclaimer:</strong><br>
    Disclaimer here.</p>
  <h3 class="try-again-link"><%= link_to "Meh?  Try again >>", "#" %></h3>
  </div>

greensmoothie/app/views/ailments/edit.html.erb
<h1>Editing ailment</h1>

<%= render 'form' %>

<%= link_to 'Show', @ailment %> |
<%= link_to 'Back', ailments_path %>

greensmoothie/app/views/ailments/index.html.erb
<br>
<div class="search-form" >
<br>
<br>
<h1 class="logo">Green Smoothie Generator</h1>

<p><h4>Switch to a collection_select drop down menu</h4></p>

<%= form_tag recipes_path, :remote => true, :method => :get do %>
  <div class="ui-widget">
      <%= search_field_tag :search, params[:search], id: "tags", class: "search-query", size: "50", :placeholder => "Select an ailment" %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-danger btn-lg", id: "search-submit" %>

      <!-- :"data-toggle" => "modal", :"data-target" => "#myModal", -->
  </div>
<% end %><br>
</div>

<div id="recipe-result">
</div>

<a href="https://twitter.com/intent/tweet?button_hashtag=GreenSmoothieGenerator&text=Generate%20a%20green%20smoothie%20based%20on%20an%20ailment" class="twitter-hashtag-button" data-lang="en" data-related="jasoncosta">Tweet #GreenSmoothieGenerator</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

greensmoothie/app/views/ailments/index.js.erb
$(function() {
  $(".search-form").hide();
  $("#recipe-result").hide().html('<%= j render(:partial => "recipe_result") %>').fadeIn(900);
  $(".try-again-link").click(function() {
    $(".search-query").val("");
    $(".search-form").fadeIn(500);
    $("#recipe-result").hide();
  });
  $(".close-out").click(function() {
    $(".search-query").val("");
    $(".search-form").fadeIn(500);
    $("#recipe-result").hide();
  });
});

greensmoothie/app/views/ailments/new.html.erb
<h1>New ailment</h1>

<%= render 'form' %>

<%= link_to 'Back', ailments_path %>

greensmoothie/app/views/ailments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ailment.name %>
</p>

<%= link_to 'Edit', edit_ailment_path(@ailment) %> |
<%= link_to 'Back', ailments_path %>