greensmoothie/config/routes.rb
Greensmoothie::Application.routes.draw do
  resources :ailments

  resources :recipes

  root 'ailments#index'

end

greensmoothie/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ailment_recipes
	has_many :ailments, through: :ailment_recipes

  # def self.normalize_recipes
  #   Recipe.all.each do |recipe|
  #     if recipe.name.include? ","
  #       normalized_recipe = recipe.name.split(",").reverse.join("").strip
  #       Recipe.find_by(:name => recipe.name).update(:name => normalized_recipe)
  #     end
  #   end
  # end

  # def self.set_actives
  #   Recipe.all.each do |recipe|
  #     @search = Ailment.search do
  #       fulltext "\"#{recipe.name}\"" do
  #         minimum_match 1
  #       end
  #     end

  #     if @search.results.size > 0
  #       recipe.active = true
  #     else
  #       recipe.active = false
  #     end

  #     recipe.save
  #   end
  # end

  # def self.active
  #   Recipe.where(:active => true)
  # end

  # def self.strip_recipes
  #   Recipe.all.each do |recipe|
  #     stripped_name = recipe.name.strip
  #     recipe.update(:name => stripped_name)
  #   end
  # end

  # def self.dedupe
  #   grouped = Recipe.all.group_by{|recipe| [recipe.name] }
  #   grouped.values.each do |duplicates|
  #     first_one = duplicates.shift
  #     duplicates.each{|double| double.destroy}
  #   end
  # end

  # def self.add_recipe(*recipes)
  #   recipes.each do |recipe|
  #     Recipe.find_or_create_by(:name => recipe.titleize, :active => true)
    #end
  #end
end

greensmoothie/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
      if params[:search].nil?
       @recipes = []
      else
        quoted_search_terms = params[:search].split(",").collect do |ailment|
        "\"+#{ailment.strip}\""
      end.join(" ")

      @recipes = []
      begin
        @search = Recipe.search do
          fulltext quoted_search_terms do
            highlight :page_content
            minimum_match 1
          end
        end

        @recipes = @search.results
        @recipes << Recipe.first if @recipes.count == 0
      rescue
        @recipes = Recipe.all.sample(5)
      end
      @recipe_name = @recipes[0..4].collect(&:name).shuffle.first
      @recipe_url = Recipe.find_by(:name => @recipe_name).try(:url)

      respond_to do |format|
        format.html { render action: "index" }
        format.js
      end
    end
  end

#end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description)
    end
end

greensmoothie/app/helpers/recipes_helper.rb
module RecipesHelper
end

greensmoothie/app/views/recipes/_form.html.erb
<div class="close-out"><%= link_to "x", "#" %></div>
  <div class="result-modal">
  <p>
    <h2 class="ailment-recipe">Here is your smoothie:</h2>
    <h2><%= link_to @recipe_name.upcase, "http://www.wikipedia.org/#{@disease_url}", :target => "blank" %></h2>
  </p>
  <%= image_tag "skull-and-crossbones.png", :id => "skull-image" %>
  <p class="disclaimer"><strong>Disclaimer:</strong><br>
    This is a humor app. We are not real doctors, and you probably don't have this rare disease. But if you are really concerned, please see a real doctor.</p>
  <h3 class="try-again-link"><%= link_to "Meh? Try again for a new recipe >>", "#" %></h3>
  </div>







<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

greensmoothie/app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

greensmoothie/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

greensmoothie/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>